name: Validador de suma

on:
  push:
    branches:
      - 'test/**'

jobs:
  operaciones:
    strategy:
      matrix:
        operacion: [suma, resta, multiplicacion, division]
    name: realizar operacion
    runs-on: ubuntu-latest
    steps:
      - name: sumar 2 numeros
        id: operacion
        env: 
          A: ${{ vars.A }}
          B: ${{ vars.B }}
          operacion: ${{ matrix.operacion }}
        run: |
          if [[ $operacion == "suma" ]]; then
            resultado=$((A+B))
          elif [[ $operacion == "resta" ]];
            resultado=$((A-B))
          elif [[ $operacion == "multiplicacion" ]];
            resultado=$((A*B))
          elif [[ $operacion == "division" ]];
            resultado=$((A/B))
          else
            echo "Operacion no soportada"
          fi
