name: upload-artifact

on:
  push:
    branches:
      - test/**

env:
  json: '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'

jobs:
  convert_and_upload_text_to_json:
    name: Convert and upload text to JSON
    runs-on: ubuntu-latest
    steps:
      - name: Crear el id unico del contenido del json
        id: hash 
        run: |
          hash=$(echo -n "${{ env.json }}" | sha256sum | cut -d ' ' -f1)
          echo hash=$hash >> $GITHUB_OUTPUT
      - name: llamar al action de cache
        uses: action/cache@v4
        id: cache
        with:
          path: archivo.json
          key: ${{ steps.hash.outputs.hash }}
      - name: Convert to JSON
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: ${{ env.json }}
          filename: 'archivo.json'
      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: archivo.json
 