name: Validador de suma

on:
  push:
    branches:
      - 'test/**'

jobs:
  suma:
    name: realizar suma
    runs-on: ubuntu-latest
    outputs:
      resultado: ${{ steps.operacion.outputs.suma }}
    steps:
      - name: sumar 2 numeros
        id: operacion
        env: 
          A: ${{ vars.A }}
          B: ${{ vars.B }}
        run: |
          resultado=$((A+B))
          echo suma=$resultado >> $GITHUB_OUTPUT
  validacion:
    name: validar si es mayor a 10
    runs-on: ubuntu-latest
    needs: suma
    steps:
      - name: Validar si la suma es mayor a 10
        env:
          res: ${{ needs.suma.outputs.resultado }}
        run: |
          if [[ $res -gt 10 ]]; then
            echo "El resultado $res es mayor a 10"
          else
            echo "El resultado $res NO es mayor a 10"
          fi
